name: "TSBookLib"
main: io.github.mg138.tsbook.Book
version: 1.0
api-version: 1.16

depend: [PlaceholderAPI, MythicMobs, ProtocolLib, Reactant, ArcticGlobal, ModularDataAccessor]

commands:
   tsbook:
      description: "Admin permissions"
      permission: tsbook.admin
      aliases: [ts, tb]
   armor:
      description: "Equipment Menu"
      permission: tsbook.armor
      aliases: [eq, equipment]
permissions:
   tsbook.admin:
      default: op
   tsbook.armor:
      default: true