name: "TSBookLib"
main: io.github.twilight_book.Book
version: 1.0
api-version: 1.16

depend: [PlaceholderAPI]

commands:
   tsbook:
      description: "Just for testing."
      permission: tsbook.test
permissions:
   tsbook.test:
      default: op
