name: "TSBookLib"
main: io.github.twilight_book.Book
version: 1.0
api-version: 1.16

depend: [PlaceholderAPI, MythicMobs, ProtocolLib]

commands:
   tsbook:
      description: "Just for testing."
      permission: tsbook.test
      aliases: [ts, tb]
permissions:
   tsbook.test:
      default: op
